version: '2.4'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - "3306:3306"
    volumes: 
      - mercadinho_data:/var/lib/mysql

volumes:
  mercadinho_data: