CREATE TABLE USUARIOS(
    CODIGO INT PRIMARY KEY IDENTITY(1,1),
    LOGIN VARCHAR(70) NOT NULL UNIQUE,
    SENHA VARCHAR(70) NOT NULL,
    NOMECOMPLETO VARCHAR(70),
    CARGO VARCHAR(70),
    ROLE VARCHAR(70) NOT NULL
);
